Atestados.UI/Controllers/Atestados/ObraArtistitaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Atestados.Datos.Modelo;
using Atestados.Negocios.Negocios;
using Atestados.Objetos.Dtos;
using Newtonsoft.Json;

namespace Atestados.UI.Controllers.Atestados
{
    public class ObraArtisticaController : Controller
    {
        private AtestadosEntities db = new AtestadosEntities();
        private InformacionAtestado infoAtestado = new InformacionAtestado();
        private InformacionGeneral infoGeneral = new InformacionGeneral();
        private string Rubro = "Obras artísticas"; // esta como otras obras profesionales
        public static List<ArchivoDTO> archivosOld = null;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            // Si la sesión es null, se redirige a la página de login
            if (Session["Usuario"] == null)
            {
                filterContext.Result = new RedirectToRouteResult(
                    new RouteValueDictionary
                    {
                        {"controller", "Login"},
                        {"action", "Index"}
                    }
                );
                return;
            }
        }

        // GET: ObraArtistica
        public ActionResult Index()
        {
            return View(infoAtestado.CargarAtestadosDeTipo(infoAtestado.ObtenerIDdeRubro(Rubro)));
        }

        // GET: ObraArtistica/Ver
        public ActionResult Ver(int? id)
        {
            UsuarioDTO usuario = (UsuarioDTO)Session["Usuario"];

            // Validar los datos ingresados.
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            AtestadoDTO atestado = infoAtestado.CargarAtestado(id);

            if (atestado == null)
                return HttpNotFound();

            // Asignar los datos para visualizar.
            ViewBag.Autores = infoAtestado.CargarAutoresAtestado(id);
            ViewBag.NotasPonderadas = infoAtestado.CargarNotasPonderadasAutores(id);
            ViewBag.Puntos = infoAtestado.CargarPuntosAutores(id);
            Session["TipoUsuario"] = usuario.TipoUsuario;
            Session["idAtestado"] = id;
            Session["idUsuario"] = usuario.UsuarioID;
            return View(atestado);
        }

        // GET: ObraArtistica/Crear
        public ActionResult Crear()
        {
            AtestadoDTO atestado = new AtestadoDTO();
            atestado.FechaInicio = DateTime.Now;
            atestado.FechaFinal = DateTime.Now;
            atestado.NumeroAutores = 1;

            ViewBag.PaisID = new SelectList(db.Pais, "PaisID", "Nombre", infoAtestado.ObtenerIDdePais("costa rica"));
            ViewBag.Atestados = infoAtestado.CargarAtestadosDePersonaPorTipo(infoAtestado.ObtenerIDdeRubro(Rubro), (int)Session["UsuarioID"]);

            //Agregar Usuario como autor
            UsuarioDTO usuario = (UsuarioDTO)Session["Usuario"];
            AutorDTO autorUsuario = new AutorDTO();
            autorUsuario.Nombre = usuario.Nombre;
            autorUsuario.PrimerApellido = usuario.PrimerApellido;
            autorUsuario.SegundoApellido = usuario.SegundoApellido;
            autorUsuario.Email = usuario.Email;
            autorUsuario.PersonaID = usuario.UsuarioID;
            autorUsuario.Porcentaje = 100;
            autorUsuario.esFuncionario = true;
            autorUsuario.porcEquitativo = false;
            autorUsuario.numAutor = 1;

            // Limpiar las listas de archivos y autores por si tienen basura.
            Session["Autores"] = new List<AutorDTO> { autorUsuario };
            Session["Archivos"] = new List<ArchivoDTO>();

            return View(atestado);
        }

        // POST: ObraArtistica/Crear
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear([Bind(Include = "AtestadoID,Nombre,NumeroAutores,Observaciones,HoraCreacion,Enviado,FechaFinal,Descargado,CantidadHoras,Lugar,CatalogoTipo,Enlace,PaisID,PersonaID,RubroID,AutoresEq,AutoresCheck")] AtestadoDTO atestado)
        {
            // Check manual para determinar si hay al menos un autor ingresado.
            if (!atestado.AutoresCheck)
                ModelState.AddModelError("AutoresCheck", "El libro debe tener al menos un autor.");
            else
            if (ModelState.IsValid)
            {
                List<AutorDTO> autores = (List<AutorDTO>)Session["Autores"];
                List<ArchivoDTO> archivos = (List<ArchivoDTO>)Session["Archivos"];

                // Obtener el id del usuario que está agregando el atestado.
                atestado.PersonaID = (int)Session["UsuarioID"];
                atestado.RubroID = infoAtestado.ObtenerIDdeRubro(Rubro);
                atestado.NumeroAutores = autores.Count();
                // Mappear el atestado una vez que está completo.
                // Esta operación es muy frágil, y podría llevar a errores de llaves en la BD.
                Atestado atestado_mapped = AutoMapper.Mapper.Map<AtestadoDTO, Atestado>(atestado);
                infoAtestado.GuardarAtestado(atestado_mapped);
                // Obtener y guardar información adicional del atestado.
                atestado.AtestadoID = atestado_mapped.AtestadoID;
                Fecha fecha = AutoMapper.Mapper.Map<AtestadoDTO, Fecha>(atestado); 
                infoAtestado.GuardarFecha(fecha);

                // Agregar archivos
                AtestadoShared.obj.guardarArchivos(archivos, infoAtestado, atestado_mapped);

                // Agregar autores
                AtestadoShared.obj.guardarAutores(autores, infoGeneral, infoAtestado, atestado.AutoresEq, atestado_mapped);

                // Limpiar las variables de sesión que contienen a los archivos y autores.
                Session["Archivos"] = new List<ArchivoDTO>();
                Session["Autores"] = new List<AutorDTO>();

                return RedirectToAction("Crear");
            }
            ViewBag.Atestados = infoAtestado.CargarAtestadosDePersonaPorTipo(infoAtestado.ObtenerIDdeRubro(Rubro), (int)Session["UsuarioID"]);
            ViewBag.PaisID = new SelectList(db.Pais, "PaisID", "Nombre", atestado.PaisID);
            return View(atestado);
        }

        // GET: ObraArtistica/Editar
        public ActionResult Editar(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            // Asegurarse que los autores y archivos no son nulos.
            if (Session["Autores"] == null)
                Session["Autores"] = new List<AutorDTO>();
            if (Session["Archivos"] == null)
                Session["Archivos"] = new List<ArchivoDTO>();

            // Cargar el atestado y verificar que no es nulo.
            Atestado atestado = infoAtestado.CargarAtestadoParaEditar(id);
            if (atestado == null)
                return HttpNotFound();

            AtestadoDTO atestado_mapped = AutoMapper.Mapper.Map<Atestado, AtestadoDTO>(atestado);

            // Cargar y poner los datos adicionales del formulario en la vista.
            ViewBag.PaisID = new SelectList(db.Pais, "PaisID", "Nombre", atestado.PaisID);
            ViewBag.Atestados = infoAtestado.CargarAtestadosDePersonaPorTipo(infoAtestado.ObtenerIDdeRubro(Rubro), (int)Session["UsuarioID"]);
            // Guardar el estado de los archivos previos a su edición.
            archivosOld = new List<ArchivoDTO>();
            List<ArchivoDTO> tmpList = infoAtestado.CargarArchivosDeAtestado(id);
            tmpList.ForEach((item) => { archivosOld.Add(new ArchivoDTO(item)); });
            Session["Archivos"] = infoAtestado.CargarArchivosDeAtestado(id);
            Session["Autores"] = infoAtestado.CargarAutoresAtestado(atestado.AtestadoID);
            indexarListas();
            return View(atestado_mapped);
        }

        // Indexar las listas de autores y archivos con números.
        private void indexarListas()
        {
            int cont = 1;
            List<ArchivoDTO> archivos = (List<ArchivoDTO>)Session["Archivos"];
            List<AutorDTO> autores = (List<AutorDTO>)Session["Autores"];

            foreach (ArchivoDTO archivo in archivos)
                archivo.numArchivo = cont++;

            cont = 1;
            foreach (AutorDTO autor in autores)
                autor.numAutor = cont++;

            Session["Archivos"] = archivos;
            Session["Autores"] = autores;
        }

        // POST: ObraArtistica/Editar
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "Lugar,CantidadHoras,Archivos,CatalogoTipo,Archivos,AtestadoID,AtestadoXPersona,Editorial,Enlace,HoraCreacion,Nombre,NumeroAutores,Observaciones,PaisID,Persona,PersonaID,RubroID,Website,Fecha,DominioIdioma,Persona,Rubro,Pais,InfoEditorial,Archivo,AutoresEq,AutoresCheck")] AtestadoDTO atestado)
        {                                          
            // Check manual para determinar si hay al menos un autor ingresado.
            if (!atestado.AutoresCheck)
                ModelState.AddModelError("AutoresCheck", "El libro debe tener al menos un autor.");
            else if (ModelState.IsValid)
            {
                List<ArchivoDTO> archivos = (List<ArchivoDTO>)Session["Archivos"];
                List<AutorDTO> autores = (List<AutorDTO>)Session["Autores"];

                atestado.PersonaID = (int)Session["UsuarioID"];

Atestados.UI/Views/ObraArtistica/Borrar.cshtml
@model Atestados.Datos.Modelo.Atestado

@{
    ViewBag.Title = "Borrar";
    Layout = "~/Views/Shared/_LayoutFuncionario.cshtml";
}



<div class="container-fluid">
    @RenderPage("~/Views/Shared/BotonRegresar.cshtml")
    <div class="mt-4">
        <h3>¿Está seguro/a que desea borrar esta obra artística?</h3>
        <hr />
    </div>
    <div class="row w-100">
        <div class="col-lg-6">
            <!-- columna izquierda -->
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nombre)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nombre)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Enlace)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Enlace)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Fecha)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Fecha.FechaFinal)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Pais)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Pais.Nombre)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Observaciones)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Observaciones)
                </dd>

            </dl>
        </div>
        <div class="col-lg-4">
            <!-- columna derecha -->
            <div class="row table-wraper scrollbar-atestados">
                <h4>Archivos</h4>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Nombre
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Archivo)
                        {
                            <tr>
                                <td>
                                    @item.Nombre
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="row table-wraper scrollbar-atestados">
                <h4>Autores</h4>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Nombre
                            </th>
                            <th>
                                Apellidos
                            </th>
                            <th>
                                Email
                            </th>
                            <th>
                                Porcentaje
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in ViewBag.Autores)
                        {
                            <tr>
                                <td>
                                    @item.Nombre
                                </td>
                                <td>
                                    @item.PrimerApellido @item.SegundoApellido
                                </td>
                                <td>
                                    @item.Email
                                </td>
                                <td>
                                    @item.Porcentaje
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" />
        </div>
    }
</div>

Atestados.UI/Views/ObraArtistica/Crear.cshtml
@model Atestados.Objetos.Dtos.AtestadoDTO

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_LayoutFuncionario.cshtml";
}

@using Atestados.Negocios.Negocios;
@using Atestados.Objetos.Dtos;

<div class="container-fluid">
    @RenderPage("~/Views/Shared/BotonRegresar.cshtml")
    <div class="mt-4">
        <h2>Obra Artística</h2>
        <hr />
    </div>
    <div class="row w-100">
        <div class="col-lg-6">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Enlace, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Enlace, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Enlace, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mb-1">
                        @Html.LabelFor(model => model.PaisID, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("PaisID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.PaisID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Fecha*</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(x => x.FechaFinal, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
                            @Html.ValidationMessageFor(model => model.FechaFinal, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mb-1">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAutores">
                            Modificar autores
                        </button>
                        @Html.ValidationMessageFor(model => model.AutoresCheck, "", new { @class = "text-danger" })
                    </div>
                    <div hidden>
                        @*Checkbox oculto porque si está dentro del modal, no devuelve el estado correctamente.*@
                        @Html.CheckBoxFor(model => model.AutoresEq)
                        @Html.CheckBoxFor(model => model.AutoresCheck)
                    </div>

                    <div class="form-group my-2">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Crear" class="btn btn-success" id="submit" />
                        </div>
                    </div>
                </div>
            }

        </div>
        <div class="col-lg-4">
            <div class="form-horizontal">
                <form id="subirArchivo">
                    <div class="form-group mb-2">
                        <div class="col-md-10">
                            <input type="file" name="archivo" id="archivo" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            <input type="submit" class="btn btn-primary" value="Subir Archivo" form="subirArchivo" />
                        </div>
                    </div>
                </form>
                @Html.Partial("_ArchivosTabla")
            </div>
        </div>
    </div>
    <div class="row table-wraper scrollbar-atestados">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        Obras Artísticas Agregadas
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (AtestadoDTO item in ViewBag.Atestados)
                {
                    <tr>
                        <td>
                            @item.Nombre
                        </td>
                        <td>
                            <a href="@Url.Action("Editar", "ObraArtistica", new { id = item.AtestadoID })" class="btn btn-warning btn-sm" title="Editar">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1rem" height="1rem" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                                </svg>
                            </a>
                            <a href="@Url.Action("Ver","ObraArtistica", new {id = item.AtestadoID})" class="btn btn-primary btn-sm" title="Ver">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#000" class="bi bi-eye" viewBox="0 0 16 16">
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
                                </svg>
                            </a>
                            <a href="@Url.Action("Borrar","ObraArtistica", new {id = item.AtestadoID})" class="btn btn-danger btn-sm" title="Borrar">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1rem" height="1rem" fill="#000" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                </svg>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@*Modal de autores.*@
<div id="modalAutores" class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="staticBackdropLabel">Modificar autores</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @Html.Partial("_AutoresTabla")
                <h3>Autor externo al Tec</h3>
                <table class="table">
                    <tr>
                        <td><input class="form-control" type="text" placeholder="Nombre" id="nombre" /></td>
                        <td><input class="form-control" type="text" placeholder="Primer apellido" id="apellido1" /></td>
                        <td><input class="form-control" type="text" placeholder="Segundo apellido" id="apellido2" /></td>
                    </tr>
                    <tr>
                        <td><input class="form-control" type="email" placeholder="Correo electrónico" id="email" /></td>
                        <td><input class="form-control" type="number" placeholder="Porcentaje" id="porcentaje" /></td>
                        <td><button type="button" class="btn btn-primary" id="autorAgregar">Agregar</button></td>
                    </tr>
                </table>
                <h3>Autor interno del Tec</h3>
                <table class="table">
                    <tr>
                        <td><input class="form-control" type="email" placeholder="Correo electrónico" id="email_funcionario" runat="server" /></td>
                        <td><input class="form-control" type="number" placeholder="Porcentaje" id="porcentaje_funcionario" /></td>
                        <td><button type="button" class="btn btn-primary" id="funcionarioAgregar">Agregar</button></td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <div class="me-auto">
                    <input class="form-check-input" type="checkbox" value="" id="hiddenCheck" name="hiddenCheck" />
                    <label class="form-check-label" for="flexCheckDefault">
                        Porcentaje equitativo
                    </label>
                </div>
                <button type="button" class="btn btn-success" data-bs-dismiss="modal">Confirmar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    @{InformacionGeneral infoGeneral = new InformacionGeneral();}
    // Esta variable debe estar en todas las vistas de atestados.
    var baseUrl = "@Variables.BaseUrl/Atestados";
    var editMode = false;
    var hasAutores = true;
</script>
@Scripts.Render("~/bundles/atestados_shared")

Atestados.UI/Views/ObraArtistica/Ver.cshtml
@model Atestados.Objetos.Dtos.AtestadoDTO

@{
    ViewBag.Title = "Ver";
    Layout = "~/Views/Shared/_LayoutFuncionario.cshtml";
}

@using Atestados.Objetos.Dtos;

<div class="container-fluid">
    @RenderPage("~/Views/Shared/BotonRegresar.cshtml")
    <div class="mt-4">
        <h2>Ver una Obra Artística</h2>
    </div>
    <hr />
    <div class="row w-100">
        <div class="col-lg-6">
            <!-- columna izquierda -->
            <dl class="dl-horizontal">
                <dt>
                    Funcionario
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Persona.Nombre)
                    @Html.DisplayFor(model => model.Persona.PrimerApellido)
                    @Html.DisplayFor(model => model.Persona.SegundoApellido)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Nombre)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nombre)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Enlace)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Enlace)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Fecha)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Fecha.FechaFinal)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Pais)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Pais.Nombre)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Observaciones)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Observaciones)
                </dd>

            </dl>
        </div>
        <div class="col-lg-4">
            <!-- columna derecha -->
            <div class="row table-wraper scrollbar-atestados">
                <h4>Archivos</h4>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Nombre
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Archivos)
                        {
                            <tr>
                                <td>
                                    @item.Nombre
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div id="nota">
                <h4>Nota ponderada:</h4>
            </div>
            @Html.Partial("Autores")
        </div>
    </div>
    <div class="row">
        <p>
            <a href="@Url.Action("Editar", "ObraArtistita", new { id = Model.AtestadoID })" class="btn btn-warning btn-sm" title="Editar">
                @Html.Partial("BotonEditar")
            </a>
            <a href="@Url.Action("Borrar", "ObraArtistita", new {id = Model.AtestadoID})" class="btn btn-danger btn-sm" title="Borrar">
                @Html.Partial("BotonBorrar")
            </a>
        </p>
    </div>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">

    var id = @Model.AtestadoID;

    $.ajax({
        type: 'POST',
        url: '@Variables.BaseUrl/Funcionario/notaAtestado',
        async: false,
        contentType: 'application/json; charset=utf-8',
        dataType: 'json',
        data: JSON.stringify({ AtestadoID: id }),
        success: function (response) {                
            if (response != null) {
                $("#nota").append('<p>' + response +'</p>')
            }
                
        }
    })

</script>