Atestados.UI/Controllers/Atestados/IdiomaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Atestados.Datos.Modelo;
using Atestados.Negocios.Negocios;
using Atestados.Objetos.Dtos;
using Newtonsoft.Json;

namespace Atestados.UI.Controllers.Atestados
{
    public class IdiomaController : Controller
    {
        private AtestadosEntities db = new AtestadosEntities();
        private InformacionAtestado infoAtestado = new InformacionAtestado();

        private readonly string Rubro = "Idiomas";
        
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            // Si la sesión es null, se redirige a la página de login
            if (Session["Usuario"] == null)
            {
                filterContext.Result = new RedirectToRouteResult(
                    new RouteValueDictionary
                    {
                        {"controller", "Login"},
                        {"action", "Index"}
                    }
                );
                return;
            }
        }
        
        // GET: Idiomas
        public ActionResult Index()
        {
            return View(infoAtestado.CargarAtestadosDeTipo(infoAtestado.ObtenerIDdeRubro(Rubro)));
        }

        // GET: Idioma/Ver
        public ActionResult Ver(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AtestadoDTO atestado = infoAtestado.CargarAtestado(id);
            if (atestado == null)
            {
                return HttpNotFound();
            }
            return View(atestado);
        }

        // GET: Idioma/Crear
        public ActionResult Crear()
        {
            IdiomaCertificadoDTO idioma = new IdiomaCertificadoDTO();
            idioma.Annio = DateTime.Now;
            idioma.Auditiva = 1;
            idioma.Oral = 1;
            idioma.Escrito = 1;
            idioma.Lectura = 1;
            idioma.IdiomaID = infoAtestado.ObtenerIdioma("inglés");

            ViewBag.IdiomaID = new SelectList(db.Idioma, "IdiomaID", "Nombre", infoAtestado.ObtenerIdioma("inglés"));
            ViewBag.Atestados = infoAtestado.CargarAtestadosDePersonaPorTipo(infoAtestado.ObtenerIDdeRubro(Rubro), (int)Session["UsuarioID"]);

            if (Session["Archivos"] == null)
            {
                Session["Archivos"] = new List<ArchivoDTO>();
            }

            return View(idioma);
        }

        // POST: Idioma/Crear
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear([Bind(Include = "Fecha,Archivos,Lugar,AtestadoID,Enlace,IdiomaID,HoraCreacion,Nombre,Observaciones,Persona,PersonaID,RubroID,Annio,Lectura,Escrito,Oral,Auditiva")] IdiomaCertificadoDTO atestado)
        {
            if (ModelState.IsValid)
            {
                atestado.PersonaID = (int)Session["UsuarioID"]; // cambiar por sesion
                atestado.RubroID = infoAtestado.ObtenerIDdeRubro(Rubro);
                atestado.PaisID = infoAtestado.ObtenerIDdePais("costa rica"); // Costa Rica
                Atestado a = AutoMapper.Mapper.Map<IdiomaCertificadoDTO, Atestado>(atestado);
                infoAtestado.GuardarAtestado(a);
                atestado.AtestadoID = a.AtestadoID;

                DominioIdioma dominio = AutoMapper.Mapper.Map<IdiomaCertificadoDTO, DominioIdioma>(atestado);
                infoAtestado.GuardarDominioIdioma(dominio);

                Fecha fecha = AutoMapper.Mapper.Map<IdiomaCertificadoDTO, Fecha>(atestado);
                infoAtestado.GuardarFecha(fecha);

                List<ArchivoDTO> archivos = (List<ArchivoDTO>)Session["Archivos"];
                foreach (ArchivoDTO archivo in archivos)
                {
                    Archivo ar = AutoMapper.Mapper.Map<ArchivoDTO, Archivo>(archivo);
                    ar.AtestadoID = a.AtestadoID;
                    infoAtestado.GuardarArchivo(ar);
                }

                Session["Archivos"] = new List<ArchivoDTO>();

                return RedirectToAction("Crear");
            }
            ViewBag.Atestados = infoAtestado.CargarAtestadosDePersonaPorTipo(infoAtestado.ObtenerIDdeRubro(Rubro), (int)Session["UsuarioID"]);
            ViewBag.IdiomaID = new SelectList(db.Idioma, "IdiomaID", "Nombre", atestado.IdiomaID);
            return View(atestado);
        }

        // GET: Idioma/Editar
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (Session["Archivos"] == null)
            {
                Session["Archivos"] = new List<ArchivoDTO>();
            }

            Atestado atestado = infoAtestado.CargarAtestadoParaEditar(id);
            AtestadoDTO a = AutoMapper.Mapper.Map<Atestado, AtestadoDTO>(atestado);
            if (atestado == null)
            {
                return HttpNotFound();
            }
            ViewBag.Atestados = infoAtestado.CargarAtestadosDePersonaPorTipo(infoAtestado.ObtenerIDdeRubro(Rubro), (int)Session["UsuarioID"]);
            ViewBag.IdiomaID = new SelectList(db.Idioma, "IdiomaID", "Nombre", atestado.DominioIdioma.IdiomaID);
            return View(a);
        }

        // POST: Idioma/Editar
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "Lugar,CantidadHoras,Archivos,AtestadoID,AtestadoXPersona,Editorial,Enlace,HoraCreacion,Nombre,NumeroAutores,Observaciones,PaisID,Persona,PersonaID,RubroID,Website,Fecha,DominioIdioma,Persona,Rubro,Pais,InfoEditorial,Archivo,Lectura,Escrito,Oral,Auditiva")] AtestadoDTO atestado)
        {
            if (ModelState.IsValid)
            {
                atestado.PersonaID = (int)Session["UsuarioID"]; // cambiar por sesion
                atestado.RubroID = infoAtestado.ObtenerIDdeRubro(Rubro);
                atestado.PaisID = infoAtestado.ObtenerIDdePais("costa rica"); // Costa Rica
                atestado.Fecha.FechaID = atestado.AtestadoID;
                atestado.Fecha.FechaInicio = DateTime.Now;
                infoAtestado.EditarFecha(AutoMapper.Mapper.Map<FechaDTO, Fecha>(atestado.Fecha));
                atestado.HoraCreacion = DateTime.Now;
                atestado.DominioIdioma.DominioIdiomaID = atestado.AtestadoID;
                infoAtestado.EditarDominioIdioma(AutoMapper.Mapper.Map<DominioIdiomaDTO, DominioIdioma>(atestado.DominioIdioma));
                atestado.Archivos = infoAtestado.CargarArchivosDeAtestado(atestado.AtestadoID);
                infoAtestado.EditarAtestado(AutoMapper.Mapper.Map<AtestadoDTO, Atestado>(atestado));

                List<ArchivoDTO> archivos = (List<ArchivoDTO>)Session["Archivos"];
                foreach (ArchivoDTO archivo in archivos)
                {
                    Archivo ar = AutoMapper.Mapper.Map<ArchivoDTO, Archivo>(archivo);
                    ar.AtestadoID = atestado.AtestadoID;
                    infoAtestado.GuardarArchivo(ar);
                }

                Session["Archivos"] = new List<ArchivoDTO>();

                return RedirectToAction("Crear");
            }

            ViewBag.Atestados = infoAtestado.CargarAtestadosDePersonaPorTipo(infoAtestado.ObtenerIDdeRubro(Rubro), (int)Session["UsuarioID"]);
            ViewBag.IdiomaID = new SelectList(db.Idioma, "IdiomaID", "Nombre", atestado.DominioIdioma.IdiomaID);
            return View(atestado);
        }

        // GET: Libro/Borrar
        public ActionResult Borrar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Atestado atestado = infoAtestado.CargarAtestadoParaBorrar(id);
            if (atestado == null)
            {
                return HttpNotFound();
            }
            return View(atestado);
        }

        // POST: Libro/Borrar
        [HttpPost, ActionName("Borrar")]
        [ValidateAntiForgeryToken]
        public ActionResult Borrar(int id)
        {
            infoAtestado.BorrarAtestado(id);
            return RedirectToAction("Crear");
        }


        [HttpPost]
        public JsonResult Cargar(HttpPostedFileBase archivo)
        {
            byte[] bytes;
            using (BinaryReader br = new BinaryReader(archivo.InputStream))
            {
                bytes = br.ReadBytes(archivo.ContentLength);
            }

            if (Session["Archivos"] == null)
            {
                Session["Archivos"] = new List<ArchivoDTO>();
            }

            ArchivoDTO ar = new ArchivoDTO
            {
                Nombre = Path.GetFileName(archivo.FileName),
                TipoArchivo = archivo.ContentType,
                Datos = bytes
            };
            List<ArchivoDTO> archivos = (List<ArchivoDTO>)Session["Archivos"];
            archivos.Add(ar);
            Session["Archivos"] = archivos;

            var jsonTest = JsonConvert.SerializeObject(ar);

            return Json(new
            {
                archivoJson = jsonTest
            });
        }

        [HttpPost]
        public FileResult Descargar(int? archivoID)
        {
            ArchivoDTO archivo = infoAtestado.CargarArchivo(archivoID);
            return File(archivo.Datos, archivo.TipoArchivo, archivo.Nombre);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Atestados.UI/Views/Idioma/Borrar.cshtml
@model Atestados.Datos.Modelo.Atestado

@{
    ViewBag.Title = "Borrar";
    Layout = "~/Views/Shared/_LayoutFuncionario.cshtml";
}

<h2>Borrar</h2>

<h3>¿Está seguro/a que desea borrar este atestado?</h3>
<div class="container-fluid">
    <div class="row">
        <h2>Idioma</h2>
        <hr />
    </div>
    <div class="row w-100">
        <div class="col-lg-6">
            <!-- columna izquierda -->
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nombre)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nombre)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Enlace)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Enlace)
                </dd>

                <dt>
                    Año
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Fecha.FechaFinal)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Lugar)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Lugar)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DominioIdioma.Idioma)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DominioIdioma.Idioma)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Observaciones)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Observaciones)
                </dd>

            </dl>
        </div>
        <div class="col-lg-4">
            <!-- columna derecha -->
            <div class="row table-wraper scrollbar-atestados">
                <h4>Archivos</h4>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Nombre
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Archivo)
                        {
                            <tr>
                                <td>
                                    @item.Nombre
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-default" />
        </div>
    }
</div>

Atestados.UI/Views/Idioma/Crear.cshtml
@model Atestados.Objetos.Dtos.IdiomaCertificadoDTO
@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_LayoutFuncionario.cshtml";
}

@using Atestados.Objetos.Dtos;

<div class="container-fluid">
    @RenderPage("~/Views/Shared/BotonRegresar.cshtml")
    <div class="mt-4">
        <h2>Idioma</h2>
        <hr />
    </div>
    <div class="row w-100">
        <div class="col-lg-6">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group mb-1">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mb-1">
                        @Html.LabelFor(model => model.Enlace, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Enlace, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Enlace, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mb-1">
                        @Html.LabelFor(model => model.Annio, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(x => x.Annio, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
                            @Html.ValidationMessageFor(model => model.Annio, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mb-1">
                        <label for="Lugar" class="control-label col-md-2">Instancia certificadora*</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Lugar, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Lugar, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.IdiomaID, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("IdiomaID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.IdiomaID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-horizontal">
                        <h4>Dominio de idioma</h4>
                        <div class="form-group mb-1">
                            @Html.LabelFor(model => model.Escrito, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                A1
                                @Html.RadioButtonFor(model => model.Escrito, 1)
                                A2
                                @Html.RadioButtonFor(model => model.Escrito, 2)
                                B1
                                @Html.RadioButtonFor(model => model.Escrito, 3)
                                B2
                                @Html.RadioButtonFor(model => model.Escrito, 4)
                                C1
                                @Html.RadioButtonFor(model => model.Escrito, 5)
                                C2
                                @Html.RadioButtonFor(model => model.Escrito, 6)
                            </div>
                        </div>
                        <div class="form-group mb-1">
                            @Html.LabelFor(model => model.Oral, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                A1
                                @Html.RadioButtonFor(model => model.Oral, 1)
                                A2
                                @Html.RadioButtonFor(model => model.Oral, 2)
                                B1
                                @Html.RadioButtonFor(model => model.Oral, 3)
                                B2
                                @Html.RadioButtonFor(model => model.Oral, 4)
                                C1
                                @Html.RadioButtonFor(model => model.Oral, 5)
                                C2
                                @Html.RadioButtonFor(model => model.Oral, 6)
                            </div>
                        </div>
                        <div class="form-group mb-1">
                            @Html.LabelFor(model => model.Auditiva, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                A1
                                @Html.RadioButtonFor(model => model.Auditiva, 1)
                                A2
                                @Html.RadioButtonFor(model => model.Auditiva, 2)
                                B1
                                @Html.RadioButtonFor(model => model.Auditiva, 3)
                                B2
                                @Html.RadioButtonFor(model => model.Auditiva, 4)
                                C1
                                @Html.RadioButtonFor(model => model.Auditiva, 5)
                                C2
                                @Html.RadioButtonFor(model => model.Auditiva, 6)
                            </div>
                        </div>
                        <div class="form-group mb-1">
                            @Html.LabelFor(model => model.Lectura, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                A1
                                @Html.RadioButtonFor(model => model.Lectura, 1)
                                A2
                                @Html.RadioButtonFor(model => model.Lectura, 2)
                                B1
                                @Html.RadioButtonFor(model => model.Lectura, 3)
                                B2
                                @Html.RadioButtonFor(model => model.Lectura, 4)
                                C1
                                @Html.RadioButtonFor(model => model.Lectura, 5)
                                C2
                                @Html.RadioButtonFor(model => model.Lectura, 6)
                            </div>
                        </div>
                    </div>

                    <div class="form-group mb-1">
                        @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group my-2">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Crear" class="btn btn-success" id="submit" />
                        </div>
                    </div>

                </div>
            }
        </div>
        <div class="col-lg-4">
            <div class="form-horizontal">
                <form id="subirArchivo">
                    <div class="form-group mb-2">
                        <div class="col-md-10">
                            <input type="file" name="archivo" id="archivo" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            <input type="submit" class="btn btn-primary" value="Subir Archivo" form="subirArchivo" />
                        </div>
                    </div>
                </form>
                @Html.Partial("_ArchivosTabla")
            </div>
        </div>
    </div>
    <div class="row table-wraper scrollbar-atestados">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Idiomas agregados</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (AtestadoDTO item in ViewBag.Atestados)
                {
                    <tr>
                        <td>
                            @item.Nombre
                        </td>
                        <td>
                            <a href="@Url.Action("Editar", "Idioma", new { id = item.AtestadoID })" class="btn btn-warning btn-sm" title="Editar">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1rem" height="1rem" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                                </svg>
                            </a>
                            <a href="@Url.Action("Ver","Idioma", new {id = item.AtestadoID})" class="btn btn-primary btn-sm" title="Ver">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#000" class="bi bi-eye" viewBox="0 0 16 16">
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
                                </svg>
                            </a>
                            <a href="@Url.Action("Borrar","Idioma", new {id = item.AtestadoID})" class="btn btn-danger btn-sm" title="Borrar">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1rem" height="1rem" fill="#000" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                </svg>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    $('#subirArchivo').submit(function (e) {
        e.preventDefault();
        var data = new FormData(this);
        if (jQuery('#archivo').val().length != '') {
            $('#archivo').val('');
            $.ajax({
                url: '@Variables.BaseUrl/Idioma/Cargar',
                data: data,
                cache: false,
                contentType: false,
                processData: false,
                type: 'POST',
                success: function (data) {
                    var archivo = JSON.parse(data.archivoJson)
                    if (data != null) {
                        $("#tablaArchivos").append('<tr><td>' + archivo.Nombre + '</td><td><a>Descargar</a> | <a>Borrar</a></td></tr>')
                    }
                }
            })
        }
    })

</script>

Atestados.UI/Views/Idioma/Ver.cshtml
@model Atestados.Objetos.Dtos.AtestadoDTO

@{
    ViewBag.Title = "Ver";
    Layout = "~/Views/Shared/_LayoutFuncionario.cshtml";
}

@using Atestados.Objetos.Dtos;

<div class="container-fluid">
    @RenderPage("~/Views/Shared/BotonRegresar.cshtml")
    <div class="mt-4">
        <h2>Idioma</h2>
        <hr />
    </div>
    <div class="row w-100">
        <div class="col-lg-6">
            <!-- columna izquierda -->
            <dl class="dl-horizontal">
                <dt>
                    Funcionario
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Persona.Nombre)
                    @Html.DisplayFor(model => model.Persona.PrimerApellido)
                    @Html.DisplayFor(model => model.Persona.SegundoApellido)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Nombre)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nombre)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Enlace)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Enlace)
                </dd>

                <dt>
                    Año
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Fecha.FechaFinal)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Lugar)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Lugar)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DominioIdioma.Idioma)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DominioIdioma.Idioma)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Observaciones)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Observaciones)
                </dd>

            </dl>
        </div>
        <div class="col-lg-4">
            <!-- columna derecha -->
            <div class="row table-wraper scrollbar-atestados">
                <h4>Archivos</h4>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Nombre
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Archivos)
                        {
                            <tr>
                                <td>
                                    @item.Nombre
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <p>
            <a href="@Url.Action("Editar", "Idioma", new { id = Model.AtestadoID })" class="btn btn-warning btn-sm" title="Editar">
                @Html.Partial("BotonEditar")
            </a>
            <a href="@Url.Action("Borrar", "Idioma", new {id = Model.AtestadoID})" class="btn btn-danger btn-sm" title="Borrar">
                @Html.Partial("BotonBorrar")
            </a>
        </p>
    </div>
</div>