Atestados.UI/Controllers/Atestados/CursoLibreController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Atestados.Datos.Modelo;
using Atestados.Negocios.Negocios;
using Atestados.Objetos.Dtos;
using Newtonsoft.Json;

namespace Atestados.UI.Controllers.Atestados
{
    public class CursoLibreController : Controller
    {
        private AtestadosEntities db = new AtestadosEntities();
        private InformacionAtestado infoAtestado = new InformacionAtestado();
        private InformacionGeneral infoGeneral = new InformacionGeneral();
        private readonly string Rubro = "Cursos libres";
        public static List<ArchivoDTO> archivosOld = null;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            // Si la sesión es null, se redirige a la página de login
            if (Session["Usuario"] == null)
            {
                filterContext.Result = new RedirectToRouteResult(
                    new RouteValueDictionary
                    {
                        {"controller", "Login"},
                        {"action", "Index"}
                    }
                );
                return;
            }
        }

        // GET: CursoLibre
        public ActionResult Index()
        {
            return View(infoAtestado.CargarAtestadosDeTipo(infoAtestado.ObtenerIDdeRubro(Rubro)));
        }

        // GET: CursoLibre/Ver
        public ActionResult Ver(int? id)
        {
            UsuarioDTO usuario = (UsuarioDTO)Session["Usuario"];

            // Validar los datos ingresados.
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            AtestadoDTO atestado = infoAtestado.CargarAtestado(id);

            if (atestado == null || atestado.RubroID != infoAtestado.ObtenerIDdeRubro(Rubro))
                return HttpNotFound();

            // Asignar los datos para visualizar.
            ViewBag.Autores = infoAtestado.CargarAutoresAtestado(id);
            ViewBag.NotasPonderadas = infoAtestado.CargarNotasPonderadasAutores(id);
            ViewBag.Puntos = infoAtestado.CargarPuntosAutores(id);
            Session["TipoUsuario"] = usuario.TipoUsuario;
            Session["idAtestado"] = id;
            Session["idUsuario"] = usuario.UsuarioID;
            return View(atestado);
        }

        // GET: CursoLibre/Crear
        public ActionResult Crear()
        {
            AtestadoDTO cursoLibre = new AtestadoDTO();
            cursoLibre.FechaFinal = DateTime.Now;
            cursoLibre.FechaInicio = DateTime.Now;
            cursoLibre.NumeroAutores = 1;
            ViewBag.Atestados = infoAtestado.CargarAtestadosDePersonaPorTipo(infoAtestado.ObtenerIDdeRubro(Rubro), (int)Session["UsuarioID"]);

            //Agregar Usuario como autor
            UsuarioDTO usuario = (UsuarioDTO)Session["Usuario"];
            AutorDTO autorUsuario = new AutorDTO();
            autorUsuario.Nombre = usuario.Nombre;
            autorUsuario.PrimerApellido = usuario.PrimerApellido;
            autorUsuario.SegundoApellido = usuario.SegundoApellido;
            autorUsuario.Email = usuario.Email;
            autorUsuario.PersonaID = usuario.UsuarioID;
            autorUsuario.Porcentaje = 100;
            autorUsuario.esFuncionario = true;
            autorUsuario.porcEquitativo = false;
            autorUsuario.numAutor = 1;

            // Limpiar las listas de archivos y autores por si tienen basura.
            Session["Autores"] = new List<AutorDTO> { autorUsuario };
            Session["Archivos"] = new List<ArchivoDTO>();

            return View(cursoLibre);
        }

        // POST: CursoLibre/Crear
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear([Bind(Include = "Fecha,Archivos,AtestadoID,AtestadoXPersona,Enlace,HoraCreacion,Nombre,CantidadHoras,Observaciones,Persona,PersonaID,RubroID,FechaInicio,FechaFinal,Lugar,NumeroAutores,AutoresEq,AutoresCheck")] AtestadoDTO atestado)
        {
            // Check manual para determinar si hay al menos un autor ingresado.
            if (!atestado.AutoresCheck)
                ModelState.AddModelError("AutoresCheck", "El curso libre debe tener al menos un autor.");
            else
            if (ModelState.IsValid)
            {
                List<AutorDTO> autores = (List<AutorDTO>)Session["Autores"];
                List<ArchivoDTO> archivos = (List<ArchivoDTO>)Session["Archivos"];

                atestado.PersonaID = (int)Session["UsuarioID"];
                atestado.RubroID = infoAtestado.ObtenerIDdeRubro(Rubro);
                atestado.PaisID = infoAtestado.ObtenerIDdePais("costa rica"); // Costa Rica
                Atestado atestado_mapped = AutoMapper.Mapper.Map<AtestadoDTO, Atestado>(atestado);
                infoAtestado.GuardarAtestado(atestado_mapped);
                atestado.AtestadoID = atestado_mapped.AtestadoID;
                Fecha fecha = AutoMapper.Mapper.Map<AtestadoDTO, Fecha>(atestado);
                infoAtestado.GuardarFecha(fecha);

                // Agregar archivos
                AtestadoShared.obj.guardarArchivos(archivos, infoAtestado, atestado_mapped);

                // Agregar autores
                AtestadoShared.obj.guardarAutores(autores, infoGeneral, infoAtestado, atestado.AutoresEq, atestado_mapped);

                // Limpiar las variables de sesión que contienen a los archivos y autores.
                Session["Archivos"] = new List<ArchivoDTO>();
                Session["Autores"] = new List<AutorDTO>();

                return RedirectToAction("Crear");
            }
            ViewBag.Atestados = infoAtestado.CargarAtestadosDePersonaPorTipo(infoAtestado.ObtenerIDdeRubro(Rubro), (int)Session["UsuarioID"]);
            return View(atestado);
        }

        // GET: CursoLibre/Borrar
        public ActionResult Borrar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Atestado atestado = infoAtestado.CargarAtestadoParaBorrar(id);
            if (atestado == null || atestado.RubroID != infoAtestado.ObtenerIDdeRubro(Rubro))
            {
                return HttpNotFound();
            }
            ViewBag.Autores = infoAtestado.CargarAutoresAtestado(id);
            return View(atestado);
        }

        // POST: CursoLibre/Borrar
        [HttpPost, ActionName("Borrar")]
        [ValidateAntiForgeryToken]
        public ActionResult Borrar(int id)
        {
            infoAtestado.BorrarAtestado(id);
            return RedirectToAction("Crear");
        }

        // GET: CursoLibre/Editar
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Asegurarse que los autores y archivos no son nulos.
            if (Session["Autores"] == null)
                Session["Autores"] = new List<AutorDTO>();
            if (Session["Archivos"] == null)
                Session["Archivos"] = new List<ArchivoDTO>();

            Atestado atestado = infoAtestado.CargarAtestadoParaEditar(id);
            AtestadoDTO atestado_mapped = AutoMapper.Mapper.Map<Atestado, AtestadoDTO>(atestado);
            if (atestado == null || atestado.RubroID != infoAtestado.ObtenerIDdeRubro(Rubro))
            {
                return HttpNotFound();
            }
            ViewBag.Atestados = infoAtestado.CargarAtestadosDePersonaPorTipo(infoAtestado.ObtenerIDdeRubro(Rubro), (int)Session["UsuarioID"]);
            // Guardar el estado de los archivos previos a su edición.
            archivosOld = new List<ArchivoDTO>();
            List<ArchivoDTO> tmpList = infoAtestado.CargarArchivosDeAtestado(id);
            tmpList.ForEach((item) => { archivosOld.Add(new ArchivoDTO(item)); });
            Session["Archivos"] = infoAtestado.CargarArchivosDeAtestado(id);
            Session["Autores"] = infoAtestado.CargarAutoresAtestado(atestado.AtestadoID);
            indexarListas();
            return View(atestado_mapped);
        }

        // Indexar las listas de autores y archivos con números.
        private void indexarListas()
        {
            int cont = 1;
            List<ArchivoDTO> archivos = (List<ArchivoDTO>)Session["Archivos"];
            List<AutorDTO> autores = (List<AutorDTO>)Session["Autores"];

            foreach (ArchivoDTO archivo in archivos)
                archivo.numArchivo = cont++;

            cont = 1;
            foreach (AutorDTO autor in autores)
                autor.numAutor = cont++;

            Session["Archivos"] = archivos;
            Session["Autores"] = autores;
        }

        // POST: CursoLibre/Editar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "Lugar,Archivos,CantidadHoras,AtestadoID,AtestadoXPersona,Enlace,HoraCreacion,Nombre,NumeroAutores,Observaciones,PaisID,Persona,PersonaID,RubroID,Website,Fecha,DominioIdioma,Persona,Rubro,Pais,InfoEditorial,Archivo,AutoresEq,AutoresCheck")] AtestadoDTO atestado)
        {
            // Check manual para determinar si hay al menos un autor ingresado.
            if (!atestado.AutoresCheck)
                ModelState.AddModelError("AutoresCheck", "El libro debe tener al menos un autor.");
            else if (ModelState.IsValid)
            {
                List<ArchivoDTO> archivos = (List<ArchivoDTO>)Session["Archivos"];
                List<AutorDTO> autores = (List<AutorDTO>)Session["Autores"];

                atestado.PersonaID = (int)Session["UsuarioID"]; // cambiar por sesion
                atestado.RubroID = infoAtestado.ObtenerIDdeRubro(Rubro);
                atestado.PaisID = infoAtestado.ObtenerIDdePais("costa rica"); // Costa Rica

Atestados.UI/Views/CursoLibre/Crear.cshtml
@model Atestados.Objetos.Dtos.AtestadoDTO

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_LayoutFuncionario.cshtml";
}

@using Atestados.Negocios.Negocios;
@using Atestados.Objetos.Dtos;

<div class="container-fluid">
    @RenderPage("~/Views/Shared/BotonRegresar.cshtml")
    <div class="mt-4">
        <h2>Curso Libre</h2>
        <hr />
    </div>

    <div class="row w-100">
        <div class="col-lg-6">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.NumeroAutores)
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Enlace, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Enlace, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Enlace, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4">Fecha de inicio*</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.FechaInicio, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
                        @Html.ValidationMessageFor(model => model.FechaInicio, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4">Fecha de finalizacion*</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.FechaFinal, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
                        @Html.ValidationMessageFor(model => model.FechaFinal, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4">Cantidad de horas*</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CantidadHoras, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CantidadHoras, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Lugar, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Lugar, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Lugar, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-1">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAutores">
                        Modificar autores
                    </button>
                    @Html.ValidationMessageFor(model => model.AutoresCheck, "", new { @class = "text-danger" })
                </div>
                <div hidden>
                    @*Checkbox oculto porque si está dentro del modal, no devuelve el estado correctamente.*@
                    @Html.CheckBoxFor(model => model.AutoresEq)
                    @Html.CheckBoxFor(model => model.AutoresCheck)
                </div>

                <div class="form-group my-2">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Crear" class="btn btn-success" id="submit" />
                    </div>
                </div>
            </div>
            }
        </div>
        <div class="col-lg-4">
            <div class="form-horizontal">
                <form id="subirArchivo">
                    <div class="form-group mb-2">
                        <div class="col-md-10">
                            <input type="file" name="archivo" id="archivo" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            <input type="submit" class="btn btn-primary" value="Subir Archivo" form="subirArchivo" />
                        </div>
                    </div>
                </form>
                @Html.Partial("_ArchivosTabla")
            </div>
        </div>
    </div>
    <div class="row table-wraper scrollbar-atestados">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Cursos libres agregados</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (AtestadoDTO item in ViewBag.Atestados)
                {
                    <tr>
                        <td>
                            @item.Nombre
                        </td>
                        <td>
                            <a href="@Url.Action("Editar", "CursoLibre", new { id = item.AtestadoID })" class="btn btn-warning btn-sm" title="Editar">
                                @Html.Partial("BotonEditar")
                            </a>
                            <a href="@Url.Action("Ver","CursoLibre", new {id = item.AtestadoID})" class="btn btn-primary btn-sm" title="Ver">
                                @Html.Partial("BotonVer")
                            </a>
                            <a href="@Url.Action("Borrar","CursoLibre", new {id = item.AtestadoID})" class="btn btn-danger btn-sm" title="Borrar">
                                @Html.Partial("BotonBorrar")
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@*Modal de autores.*@
<div id="modalAutores" class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="staticBackdropLabel">Modificar autores</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @Html.Partial("_AutoresTabla")
                <h3>Autor externo al Tec</h3>
                <table class="table">
                    <tr>
                        <td><input class="form-control" type="text" placeholder="Nombre" id="nombre" /></td>
                        <td><input class="form-control" type="text" placeholder="Primer apellido" id="apellido1" /></td>
                        <td><input class="form-control" type="text" placeholder="Segundo apellido" id="apellido2" /></td>
                    </tr>
                    <tr>
                        <td><input class="form-control" type="email" placeholder="Correo electrónico" id="email" /></td>
                        <td><input class="form-control" type="number" placeholder="Porcentaje" id="porcentaje" /></td>
                        <td><button type="button" class="btn btn-primary" id="autorAgregar">Agregar</button></td>
                    </tr>
                </table>
                <h3>Autor interno del Tec</h3>
                <table class="table">
                    <tr>
                        <td><input class="form-control" type="email" placeholder="Correo electrónico" id="email_funcionario" runat="server" /></td>
                        <td><input class="form-control" type="number" placeholder="Porcentaje" id="porcentaje_funcionario" /></td>
                        <td><button type="button" class="btn btn-primary" id="funcionarioAgregar">Agregar</button></td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <div class="me-auto">
                    <input class="form-check-input" type="checkbox" value="" id="hiddenCheck" name="hiddenCheck" />
                    <label class="form-check-label" for="flexCheckDefault">
                        Porcentaje equitativo
                    </label>
                </div>
                <button type="button" class="btn btn-success" data-bs-dismiss="modal">Confirmar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    @{InformacionGeneral infoGeneral = new InformacionGeneral();}
    // Esta variable debe estar en todas las vistas de atestados.
    var baseUrl = "@Variables.BaseUrl/Atestados";
    var editMode = false;
    var hasAutores = true;
</script>
@Scripts.Render("~/bundles/atestados_shared")

Atestados.UI/Views/CursoLibre/Editar.cshtml
@model Atestados.Objetos.Dtos.AtestadoDTO

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_LayoutFuncionario.cshtml";
}

@using Atestados.Objetos.Dtos;

<div class="container-fluid">
    @RenderPage("~/Views/Shared/BotonRegresar.cshtml")
    <div class="row">
        <h2>Editar Curso Libre</h2>
        <hr />
    </div>
    <div class="row w-100">
        <div class="col-lg-6">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.AtestadoID)
                @Html.HiddenFor(model => model.NumeroAutores)
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Enlace, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Enlace, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Enlace, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <b class="control-label col-md-2">
                            Fecha de inicio*
                        </b>
                        <div class="col-md-10">
                            @Html.TextBoxFor(x => x.Fecha.FechaInicio, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
                            @Html.ValidationMessageFor(model => model.Fecha.FechaInicio, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <b class="control-label col-md-2">
                            Fecha de finalizacion*
                        </b>
                        <div class="col-md-10">
                            @Html.TextBoxFor(x => x.Fecha.FechaFinal, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
                            @Html.ValidationMessageFor(model => model.Fecha.FechaFinal, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <b class="control-label col-md-2">
                            Cantidad de horas*
                        </b>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CantidadHoras, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CantidadHoras, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Lugar, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Lugar, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Lugar, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mb-1">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAutores">
                            Modificar autores
                        </button>
                        @Html.ValidationMessageFor(model => model.AutoresCheck, "", new { @class = "text-danger" })
                    </div>
                    <div hidden>
                        @*Checkbox oculto porque si está dentro del modal, no devuelve el estado correctamente.*@
                        @Html.CheckBoxFor(model => model.AutoresEq)
                        @Html.CheckBoxFor(model => model.AutoresCheck)
                    </div>

                    <br />

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Guardar" class="btn btn-primary" id="submit" />
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="col-lg-4">
            <div class="form-horizontal">
                <form id="subirArchivo">
                    <div class="form-group mb-2">
                        <div class="col-md-10">
                            <input type="file" name="archivo" id="archivo" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            <input type="submit" class="btn btn-primary" value="Subir Archivo" form="subirArchivo" />
                        </div>
                    </div>
                </form>
                @Html.Partial("_ArchivosTabla")
            </div>
        </div>
    </div>
    <div class="row table-wraper scrollbar-atestados">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Cursos libres agregados</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (AtestadoDTO item in ViewBag.Atestados)
                {
                    <tr>
                        <td>
                            @item.Nombre
                        </td>
                        <td>
                            <a href="@Url.Action("Editar", "CursoLibre", new { id = item.AtestadoID })" class="btn btn-warning btn-sm" title="Editar">
                                @Html.Partial("BotonEditar")
                            </a>
                            <a href="@Url.Action("Ver","CursoLibre", new {id = item.AtestadoID})" class="btn btn-primary btn-sm" title="Ver">
                                @Html.Partial("BotonVer")
                            </a>
                            <a href="@Url.Action("Borrar","CursoLibre", new {id = item.AtestadoID})" class="btn btn-danger btn-sm" title="Borrar">
                                @Html.Partial("BotonBorrar")
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div id="modalAutores" class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="staticBackdropLabel">Modificar autores</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @Html.Partial("_AutoresTabla")
                <h3>Autor externo al Tec</h3>
                <table class="table">
                    <tr>
                        <td><input class="form-control" type="text" placeholder="Nombre" id="nombre" /></td>
                        <td><input class="form-control" type="text" placeholder="Primer apellido" id="apellido1" /></td>
                        <td><input class="form-control" type="text" placeholder="Segundo apellido" id="apellido2" /></td>
                    </tr>
                    <tr>
                        <td><input class="form-control" type="email" placeholder="Correo electrónico" id="email" /></td>
                        <td><input class="form-control" type="number" placeholder="Porcentaje" id="porcentaje" /></td>
                        <td><button type="button" class="btn btn-primary" id="autorAgregar">Agregar</button></td>
                    </tr>
                </table>
                <h3>Autor interno del Tec</h3>
                <table class="table">
                    <tr>
                        <td><input class="form-control" type="email" placeholder="Correo electrónico" id="email_funcionario" runat="server" /></td>
                        <td><input class="form-control" type="number" placeholder="Porcentaje" id="porcentaje_funcionario" /></td>
                        <td><button type="button" class="btn btn-primary" id="funcionarioAgregar">Agregar</button></td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <div class="me-auto">
                    <input class="form-check-input" type="checkbox" value="" id="hiddenCheck" name="hiddenCheck" />
                    <label class="form-check-label" for="flexCheckDefault">
                        Porcentaje equitativo
                    </label>
                </div>
                <button type="button" class="btn btn-success" data-bs-dismiss="modal">Confirmar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    // Esta variable debe estar en todas las vistas de atestados.
    var baseUrl = "@Variables.BaseUrl/Atestados";
    var editMode = true;
    var hasAutores = true;
</script>
@Scripts.Render("~/bundles/atestados_shared")